import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const skills=[['Languages','Java, SQL, JavaScript, Python'],['Frontend','React.js, HTML5, CSS3, Bootstrap'],['Backend','Spring Boot, Spring Security, JDBC, REST APIs'],['Databases','MySQL, MongoDB'],['Core CS','DSA, OOP, DBMS, Operating Systems, Computer Networks'],['Tools','Git, GitHub, Postman, IntelliJ IDEA, VS Code']];
const projects=[
 {title:'RideShare Platform',tech:'Java • Spring Boot • Spring Security • JWT • Hibernate/JPA • MySQL • React.js',points:['Created a full-stack ride-sharing platform for creating rides, searching available rides, and managing bookings.','Implemented secure authentication and authorization using Spring Security and JWT.','Built booking and cancellation workflows with automatic seat availability management.','Designed a responsive React interface for search, bookings, profiles, reviews, and dashboards.']},
 {title:'Student Course Registration System',tech:'Java • Spring Boot • JDBC • MySQL • REST APIs • HTML5 • CSS3 • Bootstrap • JavaScript',points:['Developed a web application for student enrollment, course registration, and course management.','Implemented CRUD operations using MySQL, SQL queries, and foreign key constraints.','Built RESTful backend services for student, course, enrollment, and authentication modules.','Integrated backend modules and APIs for course and student management.']}
];
function App(){const [open,setOpen]=useState(false);return <><header><a className="brand" href="#home">AV</a><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">☰</button><nav className={open?'open':''}>{['About','Skills','Projects','Education','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase()} onClick={()=>setOpen(false)}>{x}</a>)}</nav></header>
<main><section id="home" className="hero"><p className="eyebrow">INTEGRATED M.TECH • COMPUTER SCIENCE</p><h1>Vasa Venkata<br/><span>Akhil Vignesh</span></h1><p className="intro">Building a strong foundation in software development, data structures, backend systems, and modern web technologies.</p><div className="actions"><a className="primary" href="#projects">View Projects</a><a className="secondary" href="mailto:vasaakhilvignesh@gmail.com">Contact Me</a></div></section>
<section id="about"><div className="label">01 / ABOUT</div><h2>A motivated Computer Science student focused on building practical software.</h2><p className="copy">I am pursuing an Integrated M.Tech in Computer Science and Engineering at VIT-AP University. My interests include Java development, backend applications, databases, data structures and algorithms, and web development.</p></section>
<section id="skills"><div className="label">02 / SKILLS</div><div className="grid">{skills.map(([a,b])=><article className="card" key={a}><h3>{a}</h3><p>{b}</p></article>)}</div></section>
<section id="projects"><div className="label">03 / PROJECTS</div><div className="projects">{projects.map((p,i)=><article className="project" key={p.title}><div className="number">0{i+1}</div><h3>{p.title}</h3><p className="tech">{p.tech}</p><ul>{p.points.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></section>
<section id="education"><div className="label">04 / EDUCATION</div><div className="timeline"><article><span>2028</span><div><h3>Integrated M.Tech in Computer Science and Engineering</h3><p>VIT-AP University • Current CGPA: 8.78</p></div></article><article><span>2023</span><div><h3>Class XII</h3><p>Andhra Pradesh Board of Intermediate Education • 96%</p></div></article><article><span>2021</span><div><h3>Class X</h3><p>Andhra Pradesh Board of Secondary Education • 100%</p></div></article></div><div className="cert"><strong>Google Cloud Digital Leader</strong><span>Certification • 2026</span></div></section>
<section id="contact" className="contact"><div><div className="label">05 / CONTACT</div><h2>Let's connect.</h2><p>For opportunities, projects, or professional communication.</p></div><div className="contactlinks"><a href="mailto:vasaakhilvignesh@gmail.com">vasaakhilvignesh@gmail.com</a><a href="tel:+919440030274">+91 94400 30274</a><a href="https://www.linkedin.com/in/akhil-vasa-494172341" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></section></main><footer>© 2026 Vasa Venkata Akhil Vignesh</footer></>}
createRoot(document.getElementById('root')).render(<App/>);
